kind: pipeline
type: docker
name: default

steps:
  - name: compile
    image: maven:3.9.4-amazoncorretto-17
    commands:
      - mvn compile
    when:
      event:
        - custom

  - name: deploy
    image: maven:3.9.4-amazoncorretto-17
    commands:
      - mvn deploy
    when:
      event:
        - custom

notify:
  - name: discord_notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: 1149981286371446815
      webhook_token:
        from_secret: aOYMldmQQOtKK82tnaYwDRzFy0pgbMAT2GMsLMQs5V-Jbojt6CTgCYkZmk_nxmlF80OO
    when:
      status: [ success, failure ]
