kind: pipeline
name: default
type: docker

steps:
  - name: fetch-version
    image: maven:3.9.4-amazoncorretto-17
    commands:
      - mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .version
  - name: compile
    image: maven:3.9.4-openjdk-17
    commands:
      - mvn -s settings.xml clean install -Dmaven.test.skip=true

  - name: notify-discord-on-success
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      text: "Build and deployment succeeded."
    when:
      status:
        - success

  - name: notify-discord-on-failure
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      text: "Build or deployment failed."
    when:
      status:
        - failure
