kind: pipeline
name: default
type: docker

steps:
  - name: fetch-version
    image: maven:3.9.4-openjdk-17
    commands:
      - mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .version

  - name: compile
    image: maven:3.9.4-openjdk-17
    commands:
      - mvn -s settings.xml clean install -Dmaven.test.skip=true

  - name: build-docker-image
    image: docker:dind
    commands:
      - export VERSION=$(cat .version)
      - docker build --build-arg JAR_FILE=target/bunny-scholar-${VERSION}.jar -t bunny-scholar:${VERSION} .

  - name: deploy
    image: docker:dind
    commands:
      - docker run -d -p 8080:8080 bunny-scholar:${VERSION}

  - name: notify-discord-on-success
    image: appleboy/drone-discord
    settings:
      webhook_id: "1150056343684784240"
      webhook_token: "fzSgcvHCx5rNexq9WkGRXQN-yuuumzlzcKmpkbbc4UAOE8OtyJD_qY09pC8J9ivL-8lU"
      text: "Build and deployment succeeded."
    when:
      status:
        - success

  - name: notify-discord-on-failure
    image: appleboy/drone-discord
    settings:
      webhook_id: "1150056343684784240"
      webhook_token: "fzSgcvHCx5rNexq9WkGRXQN-yuuumzlzcKmpkbbc4UAOE8OtyJD_qY09pC8J9ivL-8lU"
      text: "Build or deployment failed."
    when:
      status:
        - failure
